name: Trigger RIO build
description: 'triggers a build previously created on the platform'
runs:
  using: "composite"
  steps:
    - id: trigger
      run: python trigger_build.py .github/app_config/details/build_details.yaml
      shell: bash
