name: Trigger RIO build
description: 'triggers a build previously created on the platform'
runs:
  using: "composite"
  steps:
    - id: trigger
      run: .github/scripts/trigger_build/trigger_build.sh -f .github/scripts/app_config/details/build_details.yaml
      shell: bash
